### ISSUE TITLE
Custom build with Dockerfile-no-stats still reports telemetry.

### ISSUE THREAD

**Issue by dschaper** [abiosoft/caddy-docker#113]
Building with the no-stats dockerfile still shows as telemetry being sent. I've tried a few combinations of build args, environment args and can't disable stats. I donate to the project and I think that's enough, I don't need data leaked.

```
version: '3.6'

services:
  caddy:
    image: mycaddy/caddy:0.11
    container_name: caddy
    build:
      context: ./build
      dockerfile: Dockerfile-no-stats
      args:
        - plugins=filemanager,git,dnsmadeeasy
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/Caddyfile
      - type: bind
        source: ./certs
        target: /root/.caddy
    networks:
      - proxy
    ports:
      - "176.x.70.x:80:80"
      - "176.x.70.x:443:443"
    environment:
      - ACME_AGREE=true
      - DNSMADEEASY_API_KEY=${DNSME_API_KEY}
      - DNSMADEEASY_API_SECRET=${DNSME_API_SECRET}

networks:
  proxy:
    name: caddy_proxy
```
