### ISSUE TITLE
Building with gcloud plugin

### ISSUE THREAD

**Issue by alexandzors** [abiosoft/caddy-docker#135]
Currently at a loss on how to pass gcloud credentials to caddy after it is built. Here is my current compose file:

```
version: '3.3'
services:
  caddy:
    build:
      context: github.com/abiosoft/caddy-docker.git
        args:
          plugins: gcloud,geoip,nobots
    deploy:
      restart_policy:
        conditions: unless-stopped
    ports:
      - 81:80
      - 444:443
    volumes:
      - /home/docker/caddy:/etc/CaddyFile
      - /home/docker/caddy/certs:/root/.caddy
    environment:
      - "Not sure what to put here"=credentials
```
