### ISSUE TITLE
Client IP always logged as Docker network gateway 172.18.0.1

### ISSUE THREAD

**Issue by qdm12** [abiosoft/caddy-docker#142]
Hi there !

I have the problem that the only client IP Caddy would log is `172.18.0.1` - *my Docker network gateway*. Is there any way to access the client IP address without without fully exposing Caddy on the host with `--net=host`?

Thank you !

**Comment by abiosoft** [comment]
Are you using Caddy directly or as a reverse proxy? Also, can you share contents or snippets of your Caddyfile?

**Comment by qdm12** [comment]
My Docker Compose looks like:

```yml
version: '3'
services:
  caddy:
    image: abiosoft/caddy-docker
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    network_mode: bridge
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
      - ./caddy:/root/.caddy
      - ./static:/srv:ro
```

My Caddyfile:

```
https://mydomain.com {
    tls quentin.mcgaw@gmail.com
    log
    root /srv/website
}
```

I have tried accessing it with my phone using the mobile network or with a VPN but it still gives me the Docker network gateway `172.18.0.1` as client ip which is not useful for the Caddy built-in logs or ipfilter. Maybe an issue in the Caddy program? For example, I recently wrote a [simple Golang container ](https://github.com/qdm12/port-checker) which detects your public IP address successfully even when running in Docker virtual networks.

Thanks !
