### ISSUE TITLE
open /usr/share/caddy/access.log permission denied

### ISSUE THREAD

**Issue by philipposkhos** [abiosoft/caddy-docker#171]
Hi, I used docker-compose to mount the volumes to the docker container. Everything works fine until I tried to mount the log volume into the container and set a log command into the Caddyfile that came out a error 
> open /var/log/caddy/access.log: permission denied

I tried to find the online solutions (like chmod the file to 777 permission, change the log directory) but nothing helped. Is there anyone has a idea for this issue?

My caddyfile

```
 x.x.x.x:80 {
     gzip
     log /var/log/caddy/access.log {
         rotate_size 50
         rotate_age  30
         rotate_keep 20
         rotate_compress
     }
 }
```

My docker compose file
```
version: '3'
services:
    caddy:
        image: abiosoft/caddy:latest
        volumes:
            - ./CaddyCerts/:/etc/CaddyCerts
            - ./Caddyfile:/etc/Caddyfile
            - ./log/caddy/:/var/log/caddy/
        environment:
            - CADDYPATH:"/etc/CaddyCerts"
        ports:
            - "80:80"
            - "443:443"
```

My OS Version
> CentOS Linux release 7.6.1810 (Core) 

Thanks for any idea.
