### ISSUE TITLE
Can't seem to build from context with any plugins

### ISSUE THREAD

**Issue by MostHated** [abiosoft/caddy-docker#187]
Hello,  
I have been trying to add in the cloudflare plugin, as I can't seem to get Caddy to work with with any apps that use a port (docker images such as phpmyadmin, a gobuffalo application I made either in a container or standalone, etc but I can get to them if I just use the ip and port, but not with caddy) for any of my domains which all happen to go through cloudflare, so I was hoping it might help with that.

When I followed the steps I have found, I keep getting: 

    Service 'hpcs_proxy' failed to build: The command '/bin/sh -c VERSION=${version} PLUGINS=${plugins} /bin/sh /usr/bin/builder.sh' returned a non-zero code: 1

I tried doing it using this : 

    docker-compose build --no-cache hpcs_proxy

As I saw it was mentioned to use no-cache, but that has not helped any. First I tried just replicating a repo I found that had several plugins, that didn't work, so I kept removing them until I got down to just cloudflare, but that still didn't work either. Here was what I added to my docker-compose, which I think was right considering all others I came across looked like this.

```yaml

version: "3.7"

services:
  hpcs_proxy:
    build:
      context: github.com/abiosoft/caddy-docker.git
      args:
        - plugins=cloudflare # (there were a lot more at first, but this didn't work either)
    container_name: hpcs_proxy
    restart: always
    command: '-conf "/etc/caddy/Caddyfile" -agree=true  -log /etc/caddy/logs/caddy.log'
    volumes:
      - /mnt/disks/web2_data/hpcs_proxy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - hpcs_proxy_srv:/srv
      - hpcs_proxy_caddy:/root/.caddy
    ports:
      - "80:80"
      - "443:443"
      - "2015:2015"
    networks:
      - hpcs_net

volumes:
  hpcs_proxy_srv:
    driver: local
    driver_opts:
      o: bind
      device: /mnt/disks/web2_data/hpcs_proxy/srv
  hpcs_proxy_caddy:
    driver: local
    driver_opts:
      o: bind
      device: /mnt/disks/web2_data/hpcs_proxy/caddy

networks:
  hpcs_net:
    driver: bridge
    name: hpcs_data_net

```
Any suggestions would be greatly appreciated.  
Thanks,  
-MH

**Comment by abiosoft** [comment]
Use Caddy version 0.11.5 for now. There have been other reported issues with building some plugins (including Cloudflare) with Caddy 1.0 due to the new requirement of Go modules https://github.com/abiosoft/caddy-docker/issues/186 and https://github.com/abiosoft/caddy-docker/issues/185.

add version=0.11.5 to your build args.
```
build:
      context: github.com/abiosoft/caddy-docker.git
      args:
        - plugins=cloudflare
        - version=0.11.5
```
