### ISSUE TITLE
Cannot install plugin ratelimit

### ISSUE THREAD

**Issue by lpellegr** [abiosoft/caddy-docker#220]
Here is the command used:

```
docker build --build-arg plugins=ratelimit -t local/caddy github.com/abiosoft/caddy-docker.git
```

and the ouput error:

> can't load package: package caddy: 
> ratelimit.go:2:10: invalid import path: ""
> error at 'building caddy'

The plugin name `ratelimit` is found when I test with `caddyplug  install ratelimit`.

Any idea what the problem is? how can I build this great caddy image with the ratelimit plugin?

**Comment by jeslinmx** [comment]
Did something upstream break the build system? I was getting this with plugins="git,login,jwt" and so I tried:

```
  caddy:
    image: abiosoft/caddy
    build:
      context: https://github.com/abiosoft/caddy-docker.git
      args:
        # - plugins="git,login,jwt"
        # - enable_telemetry="false"
    restart: unless-stopped
    ...
```

i.e. default build variables. I got:

```
...
can't load package: package caddy: 
cors.go:2:10: invalid import path: ""
error at 'building caddy'
ERROR: Service 'caddy' failed to build: The command '/bin/sh -c VERSION=${version} PLUGINS=${plugins} ENABLE_TELEMETRY=${enable_telemetry} /bin/sh /usr/bin/builder.sh' returned a non-zero code: 1
```
