### ISSUE TITLE
Caddy Admin 2019

### ISSUE THREAD

**Issue by japrogramer** [abiosoft/caddy-docker#251]
I'm trying to access the caddy API but 
```
  caddy:
    image: abiosoft/caddy:0.11.0
    depends_on:
    - "graphql-engine"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    - "2019:2019"
    volumes:
    - ./Caddy/local-Caddyfile:/etc/Caddyfile
    - caddy_certs:/root/.caddy
``` 
And Caddyfile
```
{
    #email
    #acme_ca
}
:2019 {
    proxy / localhost:2019 {
        transparent
    }
}
```

but curl localhost:2019/config blocks forever and the log for the caddy container doesn't print anything.

what am i doing wrong?
