### ISSUE TITLE
access caddy admin /config

### ISSUE THREAD

**Issue by japrogramer** [abiosoft/caddy-docker#252]
Can't access admin 
```
run: loading initial config: loading new config: http app module: start: tcp: listening on :2019: listen tcp :2019: bind: address already in use
{"level":"info","ts":1592205213.4369204,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
{"level":"info","ts":1592205213.4729564,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
2020/06/15 07:13:33 [INFO][cache:0xc0006e0190] Started certificate maintenance routine
{"level":"info","ts":1592205213.4734793,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv1","http_port":80}
{"level":"info","ts":1592205213.4735527,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv2"}
{"level":"warn","ts":1592205213.473591,"logger":"http","msg":"user server is listening on same interface as automatic HTTP->HTTPS redirects; user-configured routes might override these redirects","server_name":"srv1","interface":"tcp/:80"}
{"level":"info","ts":1592205213.4740198,"logger":"tls","msg":"cleaned up storage units"}
run: loading initial config: loading new config: http app module: start: tcp: listening on :2019: listen tcp :2019: bind: address already in use


```
```
  caddy:
    image: caddy:2.0.0-alpine
    depends_on:
    - "graphql-engine"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    - "2019:2019"
    volumes:
    - ./Caddy/local-Caddyfile:/etc/caddy/Caddyfile
    - caddy_certs:/root/.caddy
```

```
:2019 {
    reverse_proxy / localhost:2019 {
    }
}
```
