### ISSUE TITLE
DNS issue in Kubernetes

### ISSUE THREAD

**Issue by kminehart** [abiosoft/caddy-docker#54]
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: caddy-config
data:
  Caddyfile: |-
    alerts.example.com:2015 {
      proxy / monitoring-prometheus-alertmanager:80 {
      }

      header / {
        #Include any headers for your site here
      }
      tls off
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: caddy-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: caddy
    spec:
      volumes:
      - name: caddy-config-mount
        configMap:
          name: caddy-config
          items:
          - key: Caddyfile
            path: Caddyfile
      containers:
      - name: caddy
        image: abiosoft/caddy:0.10.0
        ports:
        - containerPort: 2015
        volumeMounts:
        - name: caddy-config-mount
          mountPath: /etc
```

```
/srv # ping monitoring-prometheus-alertmanager
ping: bad address 'monitoring-prometheus-alertmanager'
```

```
/srv # cat /etc/resolv.conf
cat: can't open '/etc/resolv.conf': No such file or directory
```

```
/srv # curl 10.3.245.72
<!DOCTYPE html>
<html lang="en" ng-app="am">
<head>
...
```

```
kubectl get svc

NAME                                       CLUSTER-IP     EXTERNAL-IP      PORT(S)                      AGE
caddy-proxy                                10.3.242.17    <none>           2015/TCP                     15m
monitoring-prometheus-alertmanager         10.3.245.72    <none>           80/TCP                       4d
```
