### ISSUE TITLE
add + update ca-certificates

### ISSUE THREAD

**Issue by julianvmodesto** [abiosoft/caddy-docker#70]
I'm receiving the following error using the caddy git plugin.

```
Activating privacy features... done.
fatal: unable to access 'https://github.com/julianvmodesto/julianvmodesto.com.git/': error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
```

It seems that ca-certificates is needed.

```
apk add ca-certificates
update-ca-certificates
```

**Comment by abiosoft** [comment]
What version are you using ?

**Comment by julianvmodesto** [comment]
I'm using `abiosoft/caddy:0.10.9` on Kubernetes.

```
    spec:
      volumes:
      - name: caddyfile
        configMap:
          name: caddyfile
      containers:
      - name: caddy
        image: abiosoft/caddy:0.10.9
        ports:
        - containerPort: 2015
        volumeMounts:
        - name: caddyfile
          mountPath: /etc
```

**Comment by julianvmodesto** [comment]
Wow sorry, I fixed this by mounting a single file at /etc/Caddyfile. I saw your comment here https://github.com/abiosoft/caddy-docker/issues/54#issuecomment-298149273.

Hmm should we add an example for Kubernetes users?

```
    spec:
      volumes:
      - name: caddyfile
        configMap:
          name: caddyfile
      containers:
      - name: caddy
        image: abiosoft/caddy:0.10.9
        ports:
        - containerPort: 2015
        volumeMounts:
        - name: caddyfile
          mountPath: /etc/Caddyfile
          subPath: Caddyfile
```
