### ISSUE TITLE
Build with custom plugins fails to use new plugins list as a build argument

### ISSUE THREAD

**Issue by kidhasmoxy** [abiosoft/caddy-docker#77]
The instructions for building a custom image with a user specified plugin list no longer work with the recent updates to the builder. 

I've also tried using the instructions in the readme for a one time build separate from my compose file, and those did not change the plugins installed. These instructions use the new plugin format that was called out in my original issue #76

This section in a compose file used to work perfectly for building a new image with my desired plugins:
```
---
version: '2'
services:
  caddy:
    build:
      context: https://github.com/abiosoft/caddy-docker.git
      args:
        - plugins=authz,cache,cgi,cors,expires,filter,forwardproxy,git,grpc,ipfilter,jwt,locale,login,minify,nobots,proxyprotocol,ratelimit,realip,upload,tls.dns.googlecloud
```

Now the image builds, but the verification step lists only standard plugins, and doesn't include any of the extras requested. 

> Step 11/18 : RUN /usr/bin/caddy -plugins
>  ---> Running in dfb8e94a94ce
> Server types:
>   http
> 
> Caddyfile loaders:
>   short
>   flag
>   default
> 
> Other plugins:
>   http.basicauth
>   http.bind
>   http.browse
>   http.errors
>   http.expvar
>   http.ext
>   http.fastcgi
>   http.gzip
>   http.header
>   http.index
>   http.internal
>   http.limits
>   http.log
>   http.markdown
>   http.mime
>   http.pprof
>   http.proxy
>   http.push
>   http.redir
>   http.request_id
>   http.rewrite
>   http.root
>   http.status
>   http.templates
>   http.timeouts
>   http.websocket
>   on
>   shutdown
>   startup
>   tls
>   tls.storage.file
