### ISSUE TITLE
Docker compose invalid CIDR address when passing plugins

### ISSUE THREAD

**Issue by Siilwyn** [abiosoft/caddy-docker#78]
:wave: hi there, thanks for creating Caddy!

I ran into one issue that I can't fix or troubleshoot. Running `docker-compose build` works fine with the following configuration but running it returns and exits with code 1:

```
caddy_1            | Activating privacy features... done.
caddy_1            | 2017/11/27 22:04:03 invalid CIDR address: CIDR
```

```yaml
version: '2'
services:
  caddy:
    build:
      context: github.com/abiosoft/caddy-docker.git
      args:
        plugins: ratelimit
    volumes:
      - ./caddyfile:/etc/Caddyfile
      - ./dist:/srv
    ports:
      - 80:3000
```

This only happens when I pass the plugins in the `args` section, however I do need rate limiting.
