### ISSUE TITLE
Environment variable for tls auth missing

### ISSUE THREAD

**Issue by tomsiwik** [abiosoft/caddy-docker#89]
This is similar to the issue at:
https://caddy.community/t/caddy-tls-plugins-ignore-env-variables/2394

My digital ocean token in my `docker-compose.yml` is not recognized by the dnsprovider plugin and complains with: 

`Activating privacy features... 2018/02/22 16:03:38 DigitalOcean credentials missing`

Simplified compose file:
```yaml
caddy:
  ...
  environment:
  - DO_AUTH_TOKEN=blablabla
```

Am I missing something or is this a bug? Thanks in advance :)
